//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otw.WebApp.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otw.WebApp.Resources.Pages.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 najpopularniejszych słówek angielskich.
        /// </summary>
        internal static string DescriptionHighlight {
            get {
                return ResourceManager.GetString("DescriptionHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja do nauki.
        /// </summary>
        internal static string DescriptionPart1 {
            get {
                return ResourceManager.GetString("DescriptionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzona z myślą o osobach, które chcą w prosty i skuteczny sposób poszerzyć swoje słownictwo i utrwalić podstawowe wyrażenia w języku angielskim..
        /// </summary>
        internal static string DescriptionPart2 {
            get {
                return ResourceManager.GetString("DescriptionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryb nauki.
        /// </summary>
        internal static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryb sprawdzania.
        /// </summary>
        internal static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zapamiętywanie postępu w pamięci przeglądarki.
        /// </summary>
        internal static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responsywny interfejs – działa zarówno na komputerze, jak i telefonie.
        /// </summary>
        internal static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatyczny wygląd ciemny/jasny.
        /// </summary>
        internal static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje.
        /// </summary>
        internal static string FeaturesTitle {
            get {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod projektu na GitHub.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zacznij naukę słówek.
        /// </summary>
        internal static string StartLearningBtn {
            get {
                return ResourceManager.GetString("StartLearningBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znajdź i opanuj podręcznik, aby poznać podstawy - może być PDF z internetu..
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj 1000 najpopularniejszych słów, aby rozumieć codzienne rozmowy..
        /// </summary>
        internal static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osłuchaj się - oglądaj filmy o interesujących Cię tematach z napisami po angielsku..
        /// </summary>
        internal static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zacznij mówić - powtarzaj zdania z filmów na głos..
        /// </summary>
        internal static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauka angielskiego jest prosta.
        /// </summary>
        internal static string StepsTitle {
            get {
                return ResourceManager.GetString("StepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
